"""
Django settings for dorogaminina_django project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent


def load_config(path):
    config = {}
    if not path.exists():
        return config

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        config[key.strip()] = value.strip().strip('"').strip("'")
    return config


CONFIG = load_config(BASE_DIR / ".config")


def get_config(name, default=None):
    return os.environ.get(name, CONFIG.get(name, default))


def get_config_bool(name, default=False):
    value = get_config(name)
    return parse_bool(value, default)


def parse_bool(value, default=False):
    if value in (None, ""):
        return default
    return str(value).lower() in ("1", "true", "yes", "on")


def get_config_int(name, default=0):
    value = get_config(name)
    if value in (None, ""):
        return default
    return int(value)


def is_jino_hosting():
    return BASE_DIR.as_posix().startswith("/home/users/j/j1228127/")


DJANGO_ENV = get_config("DJANGO_ENV") or ("production" if is_jino_hosting() else "local")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_bool(os.environ.get("DJANGO_DEBUG", CONFIG.get("DEBUG")), DJANGO_ENV != "production")

MEDIA_URL = "/media/"
MEDIA_ROOT = get_config("MEDIA_ROOT") or os.path.join(BASE_DIR, "media")

STATIC_URL = "/static/"
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

if DEBUG:
    STATICFILE_DIR = os.path.join(BASE_DIR, "static")
    STATICFILES_DIRS = [
        STATICFILE_DIR,
    ]
    STATIC_ROOT = get_config("STATIC_ROOT", os.path.join(BASE_DIR, "staticfiles"))
else:
    STATIC_ROOT = get_config("STATIC_ROOT", os.path.join(BASE_DIR, "static"))

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_config("SECRET_KEY", "unsafe-local-development-key")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'robokassa',
    'smsru',
    'ckeditor',
    'import_export',
    'captcha',
    'blog',
    'home',
    'events'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dorogaminina_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dorogaminina_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if DJANGO_ENV == "local":
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
else:
    ALLOWED_HOSTS = [
        host.strip()
        for host in get_config("ALLOWED_HOSTS", "xn--80aahdwa0ajbdax.xn--p1ai,81.177.165.238").split(",")
        if host.strip()
    ]
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in get_config("CSRF_TRUSTED_ORIGINS", "https://xn--80aahdwa0ajbdax.xn--p1ai,http://xn--80aahdwa0ajbdax.xn--p1ai").split(",")
        if origin.strip()
    ]
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": get_config("MYSQL_NAME", ""),
            "USER": get_config("MYSQL_USER", ""),
            "PASSWORD": get_config("MYSQL_PASSWORD", ""),
            "HOST": get_config("MYSQL_HOST", "localhost"),
            "PORT": get_config("MYSQL_PORT", "3306"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH
AUTH_USER_MODEL = 'home.User'
AUTHENTICATION_BACKENDS = ('home.backends.AuthBackend',)

PASSWORD_DELIVERY_METHOD = get_config("PASSWORD_DELIVERY_METHOD", "email")
PASSWORD_DELIVERY_EMAIL_SUBJECT = get_config("PASSWORD_DELIVERY_EMAIL_SUBJECT", "Пароль для Дороги Минина")

EMAIL_BACKEND = get_config("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = get_config("EMAIL_HOST", "smtp.mail.ru")
EMAIL_PORT = get_config_int("EMAIL_PORT", 465)
EMAIL_HOST_USER = get_config("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_config("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_SSL = get_config_bool("EMAIL_USE_SSL", True)
EMAIL_USE_TLS = get_config_bool("EMAIL_USE_TLS", False)
DEFAULT_FROM_EMAIL = get_config("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@localhost")

SMS_RU = {
    "API_ID": get_config("SMS_RU_API_ID", ""), # если указан API ключ, логин и пароль пропускаем
    "TEST": get_config_bool("SMS_RU_TEST", False), # отправка смс в тестовом режиме, по умолчанию False
    # "SENDER": 'DorogaM', # отправитель - необязательно поле
}

ROBOKASSA_STRICT_CHECK = True
ROBOKASSA_LOGIN = get_config("ROBOKASSA_LOGIN", "")
ROBOKASSA_PASSWORD1 = get_config("ROBOKASSA_PASSWORD1", "")
ROBOKASSA_PASSWORD2 = get_config("ROBOKASSA_PASSWORD2", "")
# ROBOKASSA_TEST_MODE = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
      'file': {
          'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
      }
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
        'payment_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'payment_debug.log',
            'formatter': 'file',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'events.views': {
            'handlers': ['payment_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
