# Generated by Django 4.0.4 on 2022-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addition_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
