# Generated by Django 4.0.4 on 2022-06-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_addition_price_alter_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='event_link',
        ),
    ]
