# Generated by Django 4.0.4 on 2022-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='partner_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='partner_logo',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
