# Generated by Django 4.0.4 on 2022-06-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_place_order_order_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='order_event',
            new_name='place_event',
        ),
    ]
