# Generated by Django 4.0.4 on 2022-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_place_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Всего мест'),
        ),
        migrations.AlterField(
            model_name='place',
            name='busy',
            field=models.IntegerField(default=0, verbose_name='Занято мест'),
        ),
        migrations.AlterField(
            model_name='place',
            name='free',
            field=models.IntegerField(default=0, verbose_name='Свободно мест'),
        ),
    ]
