# Generated by Django 4.0.4 on 2022-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_place_amount_alter_place_busy_alter_place_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name': 'Футболка', 'verbose_name_plural': 'Футболки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Звено', 'verbose_name_plural': 'Звенья'},
        ),
        migrations.AddField(
            model_name='event',
            name='about_template',
            field=models.BooleanField(default=False, verbose_name='Блок О проекте'),
        ),
        migrations.AddField(
            model_name='event',
            name='blog_template',
            field=models.BooleanField(default=False, verbose_name='Блок новостей'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_template',
            field=models.BooleanField(default=False, verbose_name='Блок стоимости'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_template',
            field=models.BooleanField(default=False, verbose_name='Блок описания'),
        ),
        migrations.AddField(
            model_name='event',
            name='feedback_template',
            field=models.BooleanField(default=False, verbose_name='Блок отзывов'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_template',
            field=models.BooleanField(default=False, verbose_name='Блок галереи'),
        ),
        migrations.AddField(
            model_name='event',
            name='history_template',
            field=models.BooleanField(default=False, verbose_name='Блок исторической справки'),
        ),
        migrations.AddField(
            model_name='event',
            name='partners_template',
            field=models.BooleanField(default=False, verbose_name='Блок партнёров'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_template',
            field=models.BooleanField(default=False, verbose_name='Блок регистрации'),
        ),
        migrations.AddField(
            model_name='event',
            name='statistic_template',
            field=models.BooleanField(default=False, verbose_name='Блок статистики'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_template',
            field=models.BooleanField(default=False, verbose_name='Блок команды'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=models.FileField(upload_to='uploads/partners/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
