# Generated by Django 4.0.4 on 2022-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_options_alter_merch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='Сообщение в профайле участников'),
        ),
    ]
