# Generated by Django 4.0.4 on 2022-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон мероприятия'),
        ),
    ]
