# Generated by Django 4.0.4 on 2022-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.CharField(max_length=255, verbose_name='middlename'),
        ),
    ]
