# Generated by Django 4.0.4 on 2022-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='more',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='more'),
        ),
    ]
