# Generated by Django 4.0.4 on 2022-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_lastname_alter_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='phone number'),
        ),
    ]
