# Generated by Django 4.0.4 on 2022-06-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
    ]
